[profile.default]
src = "src"
out = "out"
libs = ["lib"]
script = "script"
test = "test"
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false
gas_reports = ["*"]
gas_reports_ignore = ["test/**/*"]
fs_permissions = [{ access = "read-write", path = "./deployments" }]


# Configuration des tests
[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 256
depth = 15
fail_on_revert = false

# Configuration pour les différents environnements
[profile.local]
src = "src"
test = "test"
script = "script"

[profile.sepolia]
src = "src"
test = "test" 
script = "script"
eth_rpc_url = "${SEPOLIA_RPC_URL}"
etherscan_api_key = "${ETHERSCAN_API_KEY}"

[profile.mainnet]
src = "src"
test = "test"
script = "script"
eth_rpc_url = "${MAINNET_RPC_URL}"
etherscan_api_key = "${ETHERSCAN_API_KEY}"

# Configuration des remappings
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@forge-std/=lib/forge-std/src/"]
